import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, describe, expect, it } from "vitest";
import { runScanCommand } from "../../src/cli/scan.js";
import { validateScanOutput } from "../../src/cli/output.js";

/**
 * VulnTrace real-world CVE validation suite.
 *
 * Unlike tests/adversarial/v1 and v2 (synthetic scenarios, a stubbed OSV
 * boundary), this suite runs the full pipeline against real, npm-installed
 * packages and real, previously-published CVEs/GHSAs, querying the REAL
 * live OSV API (no stub -- see runScanCommand's own default `provider`).
 * The point is to find gaps the synthetic suites can't: real packages use
 * real-world export idioms (UMD boilerplate, deep property assignment,
 * ...) no adversarial fixture was deliberately designed to cover.
 *
 * Same discipline as both adversarial suites: expected verdicts in
 * cases.json are the verdict a human security analyst would independently
 * derive by reading the real advisory and the real vulnerable code path --
 * never generated by running VulnTrace and copying its output. When the
 * analyzer disagrees, the case is KEPT and marked FAIL (`knownFailure:
 * true` in cases.json documents that this is a tracked, known gap, not an
 * accident) -- the oracle is never adjusted to match the tool, and the
 * analyzer is never modified just to make a case pass. See FINDINGS.md for
 * the root-cause writeup of every currently-known failure.
 *
 * Requires network access (real npm-installed fixtures are vendored, but
 * the OSV query itself is live). Not part of `npm test`/CI's default gate
 * (see vitest.validation.config.ts) -- and, while it has known failures,
 * deliberately not added to CI at all yet (see package.json/CI history).
 */

interface ValidationCase {
  readonly id: string;
  readonly dir: string;
  readonly package: string;
  readonly version: string;
  readonly vulnerability: string;
  readonly aliases: readonly string[];
  readonly advisoryUrl: string;
  readonly vulnerableTarget: string;
  readonly description: string;
  readonly expected: "AFFECTED" | "NOT_AFFECTED" | "UNKNOWN";
  readonly knownFailure: boolean;
  readonly reason: string;
  readonly findingSelector: {
    readonly package: string;
    readonly version: string;
    readonly vulnerability: string;
  };
}

interface CaseResult {
  readonly id: string;
  readonly description: string;
  readonly expected: string;
  readonly actual: string;
  readonly pass: boolean;
  readonly knownFailure: boolean;
}

const REPO_ROOT = path.resolve(
  fileURLToPath(new URL("../../", import.meta.url)),
);
const SUITE_ROOT = path.join(REPO_ROOT, "tests", "validation");
const FIXTURES_ROOT = path.join(SUITE_ROOT, "fixtures");
const REPORT_PATH = path.join(SUITE_ROOT, "REPORT.md");

const cases: readonly ValidationCase[] = JSON.parse(
  readFileSync(path.join(SUITE_ROOT, "cases", "cases.json"), "utf-8"),
) as ValidationCase[];

function fakeIo() {
  const stdout: string[] = [];
  const stderr: string[] = [];
  return {
    io: {
      stdout: (t: string) => stdout.push(t),
      stderr: (t: string) => stderr.push(t),
    },
    stdout,
    stderr,
  };
}

const results: CaseResult[] = [];

describe("VulnTrace real-world CVE validation suite", () => {
  for (const testCase of cases) {
    it(`${testCase.id} ${testCase.description}`, async () => {
      const fixtureDir = path.join(FIXTURES_ROOT, testCase.dir);
      const { io, stdout, stderr } = fakeIo();

      // provider intentionally omitted -- runScanCommand defaults to a
      // real OsvProvider, so this hits the live OSV API.
      const exitCode = await runScanCommand({
        projectPathArg: fixtureDir,
        configPathOverride: path.join(fixtureDir, "vulntrace.yml"),
        noCache: true,
        io,
      });

      let actual = "NO_OUTPUT";
      let schemaIssues: unknown[] = [];
      try {
        const output = JSON.parse(stdout.join("")) as {
          findings: ReadonlyArray<{
            package: string;
            version: string;
            vulnerability: string;
            verdict: string;
          }>;
        };
        schemaIssues = validateScanOutput(output);
        // Real OSV data can carry multiple, mutually-aliased advisory ids
        // for the same underlying vulnerability (confirmed live for
        // GHSA-35jh-r3h4-6jhm / GHSA-r5fr-rjxr-66jc, both CVE-2021-23337)
        // -- unlike the synthetic suites, package+version alone isn't a
        // unique selector here.
        const match = output.findings.find(
          (f) =>
            f.package === testCase.findingSelector.package &&
            f.version === testCase.findingSelector.version &&
            f.vulnerability === testCase.findingSelector.vulnerability,
        );
        actual = match ? match.verdict : "NO_FINDING";
      } catch {
        actual = "UNPARSEABLE_OUTPUT";
      }

      results.push({
        id: testCase.id,
        description: testCase.description,
        expected: testCase.expected,
        actual,
        pass: actual === testCase.expected,
        knownFailure: testCase.knownFailure,
      });

      expect(
        schemaIssues,
        `${testCase.id}: exit ${exitCode}, stderr: ${stderr.join("")}`,
      ).toEqual([]);
      expect(
        actual,
        `${testCase.id} (${testCase.vulnerability}): expected ${testCase.expected}, got ${actual}.\n` +
          `Human rationale: ${testCase.reason}\n` +
          `stderr: ${stderr.join("")}`,
      ).toBe(testCase.expected);
    });
  }

  afterAll(() => {
    writeReport();
    printTable();
  });
});

function printTable(): void {
  const rows = [...results].sort((a, b) => a.id.localeCompare(b.id));
  const lines: string[] = [];
  lines.push("ID       EXPECTED        ACTUAL          RESULT");
  lines.push("------------------------------------------------");
  for (const r of rows) {
    const flag = !r.pass && r.knownFailure ? " (known)" : "";
    lines.push(
      r.id.padEnd(9) +
        r.expected.padEnd(16) +
        r.actual.padEnd(16) +
        (r.pass ? "PASS" : "FAIL") +
        flag,
    );
  }
  const passed = rows.filter((r) => r.pass).length;
  const unexpectedFailures = rows.filter((r) => !r.pass && !r.knownFailure);
  lines.push("------------------------------------------------");
  lines.push(
    `${passed}/${rows.length} passed (${((passed / rows.length) * 100).toFixed(1)}%)`,
  );
  lines.push(
    `Unexpected failures (not in FINDINGS.md): ${unexpectedFailures.length}`,
  );
  console.log("\n" + lines.join("\n") + "\n");
}

function writeReport(): void {
  const rows = [...results].sort((a, b) => a.id.localeCompare(b.id));
  const total = rows.length;
  const passed = rows.filter((r) => r.pass).length;
  const failed = total - passed;
  const knownFailures = rows.filter((r) => !r.pass && r.knownFailure);
  const unexpectedFailures = rows.filter((r) => !r.pass && !r.knownFailure);

  const lines: string[] = [];
  lines.push("# VulnTrace Real-World CVE Validation Report");
  lines.push("");
  lines.push(
    "Generated by `npm run test:validation` (`tests/validation/validation.test.ts`). " +
      "Expected verdicts come from `tests/validation/cases/cases.json`, authored " +
      "independently of VulnTrace's own output by reading each case's real advisory " +
      "and real vulnerable code path. Uses the real, live OSV API -- not stubbed.",
  );
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- Total cases: ${total}`);
  lines.push(`- Passed: ${passed}`);
  lines.push(`- Failed: ${failed}`);
  lines.push(`  - Known (tracked in FINDINGS.md): ${knownFailures.length}`);
  lines.push(`  - Unexpected: ${unexpectedFailures.length}`);
  lines.push("");
  lines.push("## Result table");
  lines.push("");
  lines.push("```");
  lines.push("ID       EXPECTED        ACTUAL          RESULT");
  lines.push("------------------------------------------------");
  for (const r of rows) {
    const flag = !r.pass && r.knownFailure ? " (known)" : "";
    lines.push(
      r.id.padEnd(9) +
        r.expected.padEnd(16) +
        r.actual.padEnd(16) +
        (r.pass ? "PASS" : "FAIL") +
        flag,
    );
  }
  lines.push("```");
  lines.push("");
  if (unexpectedFailures.length > 0) {
    lines.push("## ⚠ Unexpected failures -- not yet in FINDINGS.md");
    lines.push("");
    lines.push(
      "These disagree with the oracle and are NOT marked `knownFailure` in " +
        "cases.json. Investigate and add a FINDINGS.md entry (or fix the bug) " +
        "before considering this run clean.",
    );
    lines.push("");
    for (const r of unexpectedFailures) {
      lines.push(
        `- ${r.id}: ${r.description} (expected ${r.expected}, got ${r.actual})`,
      );
    }
    lines.push("");
  }
  if (knownFailures.length > 0) {
    lines.push("## Known failures (tracked)");
    lines.push("");
    for (const r of knownFailures) {
      const c = cases.find((x) => x.id === r.id);
      lines.push(`- ${r.id}: ${r.description}`);
      if (c) {
        lines.push(`  - ${c.reason}`);
      }
    }
    lines.push("");
  }

  mkdirSync(path.dirname(REPORT_PATH), { recursive: true });
  writeFileSync(REPORT_PATH, lines.join("\n") + "\n");
}
